# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'
  
jobs:
- job: Build
  displayName: 'Build and Test'
  steps:
  - task: UseXcode@7
    inputs:
      version: '12'
      useXcodeSelect: true

  - script: |
      xcodebuild clean build -workspace MoviesTunnel.xcworkspace -scheme MoviesTunnel -destination 'platform=iOS Simulator,name=iPhone 12'

  - script: |
      xcodebuild test -workspace MoviesTunnel.xcworkspace -scheme MoviesTunnel -destination 'platform=iOS Simulator,name=iPhone 12'
